const SET_ITEM = 'SET_ITEM'
const REMOVE_ITEM = 'REMOVE_ITEM'
const SET_COMMENT = 'SET_COMMENT'
const REMOVE_COMMENTS = 'REMOVE_COMMENTS'

export default {
  SET_ITEM,
  REMOVE_ITEM,
  SET_COMMENT,
  REMOVE_COMMENTS
}
